services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      CI_ENVIRONMENT: production
      app.baseURL: http://13.229.16.216:8080