services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      CI_ENVIRONMENT: development
      # app.baseURL: https://simrs.dedeard.my.id
      app.baseURL: http://13.229.16.216:8080
      DB_HOST: 127.0.0.1
      DB_PORT: 3300
      DB_DATABASE: simrs
      DB_USERNAME: simrs
      DB_PASSWORD: simrs

  mysql:
    image: mysql:8.0
    ports:
      - "3300:3306"
    environment:
      MYSQL_DATABASE: simrs
      MYSQL_USER: simrs
      MYSQL_PASSWORD: simrs
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: