services:
  mysql:
    image: mysql:latest
    container_name: mysql-server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: simrs
      MYSQL_USER: simrs
      MYSQL_PASSWORD: simrs
      MYSQL_ROOT_HOST: '%'      # Allow connections from any host
    command: 
      - --bind-address=0.0.0.0  # Listen on all network interfaces
    volumes:
      - mysql-data:/var/lib/mysql
    

configs:
  mysql_config:
    content: |
      [mysqld]
      bind-address = 0.0.0.0
      skip-name-resolve

volumes:
  mysql-data: