services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      CI_ENVIRONMENT: development
      DB_HOST: mysql
      DB_DATABASE: ci4_app
      DB_USERNAME: ci4user
      DB_PASSWORD: ci4password

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ci4_app
      MYSQL_USER: ci4user
      MYSQL_PASSWORD: ci4password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: